### ISSUE TITLE
DB not found: operational error when starting ARM

### ISSUE THREAD

**Issue by johnhelt** [automatic-ripping-machine/automatic-ripping-machine#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Whenever I try to run ARM using the docker setup (start_arm_container.sh), I get the error

``sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
``

### To Reproduce

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

Docker version 25.0.3, build 4debf41

sudo ./start_arm_container.sh

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

I would expect the UI to be available, and the database creation to occur without issues.

### Relevant log output

```shell
*** Running /etc/my_init.d/10_syslog-ng.init...
Feb 18 23:19:06 18b7bb4e8141 syslog-ng[13]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm user id from 1000 to 1001...
Updating arm group id from 1000 to 1002...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1002
Creating dir: /home/arm/db
Removing any link between music and Music
Checking ownership of /etc/arm/config
[OK]: ARM UID and GID set correctly, ARM has access to '/etc/arm/config' using 1001:1002
Checking location of abcde configuration files
/etc/abcde.conf link doesnt exist
*** Running /etc/my_init.d/start_udev.sh...
/etc/my_init.d/start_udev.sh: 0: can't access tty; job control turned off
# # # # Trying to start udev
# #
udev Started successfully
*** Booting runit daemon...
*** Runit started as PID 115
Starting web ui
Feb 18 23:19:08 18b7bb4e8141 cron[118]: (CRON) INFO (pidfile fd = 3)
Feb 18 23:19:08 18b7bb4e8141 cron[118]: (CRON) INFO (Running @reboot jobs)
[2024-02-18 23:19:08,523] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-02-18 23:19:08,594] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-02-18 23:19:08,594] DEBUG ARM: utils.arm_db_check Database file is not present: /home/arm/db/arm.db
[2024-02-18 23:19:08,594] DEBUG ARM: utils.arm_db_cfg No armui cfg setup
[2024-02-18 23:19:08,594] INFO ARM: utils.check_db_version No database found.  Initializing arm.db...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import db  # needs to be imported before models
  File "/opt/arm/arm/../arm/ui/__init__.py", line 66, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 28, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 206, in arm_db_cfg
    check_db_version(cfg.arm_config['INSTALLPATH'], cfg.arm_config['DBFILE'])
  File "/opt/arm/arm/../arm/ui/utils.py", line 88, in check_db_version
    flask_migrate.upgrade(mig_dir)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 399, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "/opt/arm/arm/migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "/opt/arm/arm/migrations/env.py", line 73, in run_migrations_online
    connection = engine.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Starting web ui
[2024-02-18 23:19:10,146] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-02-18 23:19:10,197] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-02-18 23:19:10,198] DEBUG ARM: utils.arm_db_check Database file is not present: /home/arm/db/arm.db
[2024-02-18 23:19:10,198] DEBUG ARM: utils.arm_db_cfg No armui cfg setup
[2024-02-18 23:19:10,198] INFO ARM: utils.check_db_version No database found.  Initializing arm.db...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import db  # needs to be imported before models
  File "/opt/arm/arm/../arm/ui/__init__.py", line 66, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 28, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 206, in arm_db_cfg
    check_db_version(cfg.arm_config['INSTALLPATH'], cfg.arm_config['DBFILE'])
  File "/opt/arm/arm/../arm/ui/utils.py", line 88, in check_db_version
    flask_migrate.upgrade(mig_dir)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 399, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "/opt/arm/arm/migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "/opt/arm/arm/migrations/env.py", line 73, in run_migrations_online
    connection = engine.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
^C*** Shutting down runit daemon (PID 115)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Feb 18 23:19:11 18b7bb4e8141 syslog-ng[13]: syslog-ng shutting down; version='3.25.1'
*** Init system aborted.
*** Killing all processes...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by upsj** [comment]
Had the same issue in the `latest` Docker container, I somehow managed to convince `runui.py` to create a database file when running it as `root` inside a running container, but this is of course not a general solution.

**Comment by microtechno9000** [comment]
The last PR modified ARM to not change ownership of mounted volumes as that creates interesting functional and security issues. Seems that something is not creating folders with the correct permissions.

Can you run the below and past the output please

`ls -laR /home/arm`

The simple fix is to chown the /home/arm folder to be owned by arm:arm. If you run this, please do after getting the above output.

`sudo chown -R arm:arm /home/arm`

**Comment by johnhelt** [comment]
I see, db is owned by root. Here's the output from:

``ls -laR /home/arm``


----------------

```/home/arm/db:
total 8
drwxr-xr-x  2 root root 4096 Feb 19 00:19 .
drwxr-x--- 12 arm  arm  4096 Feb 19 00:19 ..

/home/arm/.local:
total 12
drwxrwxr-x  3 arm arm 4096 Feb 18 23:52 .
drwxr-x--- 12 arm arm 4096 Feb 19 00:19 ..
drwx------  4 arm arm 4096 Feb 19 00:01 share

/home/arm/.local/share:
total 16
drwx------ 4 arm arm 4096 Feb 19 00:01 .
drwxrwxr-x 3 arm arm 4096 Feb 18 23:52 ..
drwx------ 2 arm arm 4096 Feb 19 00:01 mc
drwx------ 2 arm arm 4096 Feb 19 00:03 nano

/home/arm/.local/share/mc:
total 12
drwx------ 2 arm arm 4096 Feb 19 00:01 .
drwx------ 4 arm arm 4096 Feb 19 00:01 ..
-rw------- 1 arm arm   92 Feb 19 00:01 history

/home/arm/.local/share/nano:
total 12
drwx------ 2 arm arm 4096 Feb 19 00:03 .
drwx------ 4 arm arm 4096 Feb 19 00:01 ..
-rw------- 1 arm arm   22 Feb 19 00:03 search_history

/home/arm/logs:
total 12
drwxrwxr-x  3 arm  arm  4096 Feb 18 23:59 .
drwxr-x--- 12 arm  arm  4096 Feb 19 00:19 ..
drwxr-xr-x  2 root root 4096 Feb 18 23:59 progress

/home/arm/logs/progress:
total 8
drwxr-xr-x 2 root root 4096 Feb 18 23:59 .
drwxrwxr-x 3 arm  arm  4096 Feb 18 23:59 ..

/home/arm/.MakeMKV:
total 8
drwxr-xr-x  2 root root 4096 Feb 18 23:59 .
drwxr-x--- 12 arm  arm  4096 Feb 19 00:19 ..

/home/arm/media:
total 8
drwxr-xr-x  2 root root 4096 Feb 18 23:59 .
drwxr-x--- 12 arm  arm  4096 Feb 19 00:19 ..

/home/arm/music:
total 8
drwxr-xr-x  2 root root 4096 Feb 18 23:59 .
drwxr-x--- 12 arm  arm  4096 Feb 19 00:19 ..

/home/arm/Music:
total 8
drwxr-xr-x  2 root root 4096 Feb 18 23:59 .
drwxr-x--- 12 arm  arm  4096 Feb 19 00:19 ..
```


I guess the Music/music folders are because of a mistake in volume binding?

> The simple fix is to chown the /home/arm folder to be owned by arm:arm. If you run this, please do after getting the above output.

Changing this did indeed fix the issue.
Thanks for your support.

**Comment by microtechno9000** [comment]
reopening issue, as the issue is still present when building ARM

**Comment by microtechno9000** [comment]
Resolved with recent PR's to arm-dependencies and ARM

**Comment by ltomes** [comment]
I setup ARM for the first time today on latest (2.6.71) and still had to run `chown -R arm:arm /home/arm`  to get first boot.

**Comment by microtechno9000** [comment]
What volumes are you using and what permissions did they have prior to changing ownership?

**Comment by ltomes** [comment]
> What volumes are you using and what permissions did they have prior to changing ownership?

The /home/arm/music directory was mounted from the host filesystem and had a different owner. Unfortunately I didn't screenshot the command output to put on this ticket.

**Comment by Sentennial** [comment]
I believe this is still an issue ( at least with the latest docker image v[2.6.72] )

I ran the scripts/docker-setup.sh, confirmed arm:arm existed (id 1001:1001), created folders as such:
```
mkdir config  home  logs  media  music
sudo chown -R 1001:1001 config home logs media music
sudo chmod -R 777 config home logs media music
```
Then ran the container. The container created the /home/db folder, but it created it with the root user, so the arm user cannot access it.
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/121533452/71ef2a48-8678-43b9-ac69-5397f6f930e9)

In order to run the container, it has to be stopped after first run, then redo the chown command to recursively own everything.

**Comment by Sentennial** [comment]
If we edited arm_user_files_setup.sh at https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/58e00311992dfb375e50c16a64f40c4fcac933bb/scripts/docker/runit/arm_user_files_setup.sh#L67
And changed `mkdir -p "$thisDir"` to `su -uarm mkdir -m0755 -p "$thisDir"`
That would help
