### ISSUE TITLE
🐛 Disc ID Issue

### ISSUE THREAD

**Issue by polskikrol** [automatic-ripping-machine/automatic-ripping-machine#1394]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### I have checked the wiki

- [x] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [x] I'm using the latest release

### Describe the bug?

Using a docker container with the latest version, I receive an error whereas the disc cannot be authenticated. Illegal Request. Looking into this, looks like ARM is malforming the access request:

` makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'`

DiscID 9999 does not exist. Strange thing, in the GUI, the drive is properly identified as /dev/sr0 for the mount path. So, why doesnt ARM just do the following instead:

` makemkvcon -r info dev:/dev/sr0 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'`

Alternatively, the DiscID should be mapped correctly to use ID 0.

Now, not sure what this condition is testing, but I think the GREP is broken. Please see the following:

```
root@arm:/home/arm# makemkvcon -r info dev:/dev/sr0 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'
0
root@arm:/home/arm# makemkvcon -r info disc:0 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'
0
```

If we remove the grep, the results are all the same:

```
root@arm:/home/arm# makemkvcon -r info disc:0 | grep /dev/sr0
DRV:0,2,999,1,"BD-RE TSSTcorp BDDVDW SE-506CB TS02 REDACTED","AVIATOR","/dev/sr0"
root@arm:/home/arm# makemkvcon -r info disc:9999 | grep /dev/sr0
DRV:0,2,999,1,"BD-RE TSSTcorp BDDVDW SE-506CB TS02 REDACTED","AVIATOR","/dev/sr0"
root@arm:/home/arm# makemkvcon -r info dev:/dev/sr0 | grep /dev/sr0
DRV:0,2,999,1,"BD-RE TSSTcorp BDDVDW SE-506CB TS02 REDACTED","AVIATOR","/dev/sr0"
```
Here is the actual ARM log error for the rip:

```
[05-19-2025 17:39:44] DEBUG ARM: makemkv.makemkv Using command: makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'
[05-19-2025 17:39:45] ERROR ARM: makemkv.__init__ Call to MakeMKV failed with code: 1 (b'')
[05-19-2025 17:39:45] ERROR ARM: arm_ripper.rip_visual_media MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
```

In my testing, I had also upgraded makemkvcon to version 1.18.1.

### To Reproduce

Please see above.

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

```
root@arm:/home/arm# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

automaticrippingmachine/automatic-ripping-machine:latest

Python version: 3.10.12
A.R.M version: 2.13.0
Current git version: 1122d0e

### Expected behavior?

Manually running the ripping commands works.

### Relevant log output

```shell
Please see above.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by polskikrol** [comment]
Dang, created this as a regular issue.. should be flagged as a docker-related issue. Cant figure out how to reflag it.

**Comment by microtechno9000** [comment]
Looking back through the code, the `makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'` command hasn't been updated for over 8 years, having been there since the dawn of time.

The handling of the MakeMKV code is not my expertise, and the makemkvcon help files and documentation isn't that great.

Looks like the logic is:
1. Get disc id
2. rip disc using the disc id (my old logs are either 0 or 1, for the two drives I have)

As you note, there is nothing wrong with using the /dev id, unless there was some unknown reason for this
@shitwolfymakes thoughts?

**Comment by polskikrol** [comment]
Any idea why this may be failing though? Doesnt matter to me if it is referenced by dev or id, although, why not have a user setting where the CD drives are enumerated and you can a) enable/disable for ripping, and b) maybe see the dev and id mappings.

Currently, for some reason, I presume that ARM is coming up with disc ID 9999 for some reason, which of course doesnt exist. So, that code fails. Although, even if I run the code with the grep using the correct disc ID, the output looks similar. In either case, the ARM scripts fail to rip when invoking the makeMKV scripts, but running manually with the commands from a docker bash works.

(I have also run the install_makemkv and handbrake scripts within the container to make sure both are updated, and still run into the same issue. On a side note, going to write a similar script to auto-install the libraries/tools for QSV. I see most of the build environment is now included in newer docker images, so much of my previously posted commands to install missing packages are not needed. But autopulling and verifying the intel scripts would be good. Going to see if I can modify to run the scripts based on an environment variable passed via the docker compose file.)

**Comment by polskikrol** [comment]
Ok, so I looked a bit more deeply into your code... to be honest, I had misunderstood what was causing the actual issue! You are using subprocess calls and it was coming up with an error:

returned non-zero exit status 1 

There were more logs, but they just rolled, boo.

So, I tested your code snippet via some test python code:

```
#!/usr/bin/env python3
import os
import logging
import subprocess


class MakeMkvRuntimeError(RuntimeError):
    def __init__(self, error):
        self.message = f"Call to MakeMKV failed with code: {error.returncode} ({error.output})"
        logging.error(self.message)
        raise super().__init__(self.message)

cmd = f"makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'"
print(f"Using command: {cmd}")
try:
    mdisc = subprocess.check_output(
        cmd,
        shell=True,
    ).decode("utf-8")
    print(f"MakeMKV disc number: {mdisc.strip()}")
    print(f"Disk raw number: {mdisc}")
except subprocess.CalledProcessError as mdisc_error:
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
```

This all worked fine with expected output:

```
MakeMKV disc number: 0
Disk raw number: 0
```

I did not a few other things... not all of the imported py scripts have the correct permissions for execute:

root@arm:/opt/arm/arm/ripper# ls -la
total 176
drwxr-xr-x 1 arm  arm   4096 May 29 13:05 .
drwxr-xr-x 1 arm  arm   4096 May 22 05:02 ..
-rwxr-xr-x 1 arm  arm   7434 May 22 00:43 apprise_bulk.py
-rw-r--r-- 1 arm  arm   3634 May 22 00:43 ARMInfo.py
-rwxr-xr-x 1 arm  arm  10887 May 22 00:43 arm_ripper.py
-rw-r--r-- 1 arm  arm  13745 May 22 00:43 handbrake.py
-rwxr-xr-x 1 arm  arm  13513 May 22 00:43 identify.py
-rwxr-xr-x 1 arm  arm    163 May 22 00:43 __init__.py
-rwxr-xr-x 1 arm  arm   5131 May 22 00:43 logger.py
-rw-r--r-- 1 arm  arm   9863 May 22 00:43 main.py
-rw-r--r-- 1 arm  arm  16893 May 22 00:43 makemkv.py
-rwxr-xr-x 1 arm  arm   9246 May 22 00:43 music_brainz.py
-rw-r--r-- 1 arm  arm    555 May 22 00:43 ProcessHandler.py
drwxr-xr-x 2 arm  arm   4096 May 22 05:02 __pycache__
-rwxr-xr-x 1 root root   731 May 29 13:03 test.py
-rwxr-xr-x 1 arm  arm  33567 May 22 00:43 utils.py

So, I corrected this by chmod 755 on the files here.

Additionally, there was a docker container update via apt in Ubuntu.

Testing again, things work!

So.... this issue is resolved for now. Initially I thought it was Apparmor flagging a subprocess task or something, but your project only needs to have mount permissions (I already outlined this in another post). So not sure if fixing permissions or the docker update fixed this issue.

I would however, at least update the code base so that these files have the correct executable bit set permissions.

**Comment by ynnckvdv** [comment]
I'm running into this too. Sadly setting the permissions of the Python scripts to `755` did not fix it for me.
Your test script worked fine for me though:

```
root@truenas:~-# python3 test.py
Using command: makemkvcon -r info disc:9999 | grep /dev/sr1 | grep -oP '(?<=:).*(?=)'
MakeMKV disc number: 0
Disk raw number: 0

root@truenas:~-# python3 test.py
Using command: makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*(?=)'
MakeMKV disc number: 1
Disk raw number: 1
```

Looks fine, even though `/dev/sr1` is assigned to disc 0 and `/dev/sr0` is assigned to disc 1. But I don't believe that's causing the issue, because I have the same issue when only passing one drive through.

**Comment by microtechno9000** [comment]
> Ok, so I looked a bit more deeply into your code... to be honest, I had misunderstood what was causing the actual issue! You are using subprocess calls and it was coming up with an error:
> 
> returned non-zero exit status 1 
> 
> There were more logs, but they just rolled, boo.
> 
> So, I tested your code snippet via some test python code:
> 
> ```
> #!/usr/bin/env python3
> import os
> import logging
> import subprocess
> 
> 
> class MakeMkvRuntimeError(RuntimeError):
>     def __init__(self, error):
>         self.message = f"Call to MakeMKV failed with code: {error.returncode} ({error.output})"
>         logging.error(self.message)
>         raise super().__init__(self.message)
> 
> cmd = f"makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'"
> print(f"Using command: {cmd}")
> try:
>     mdisc = subprocess.check_output(
>         cmd,
>         shell=True,
>     ).decode("utf-8")
>     print(f"MakeMKV disc number: {mdisc.strip()}")
>     print(f"Disk raw number: {mdisc}")
> except subprocess.CalledProcessError as mdisc_error:
>     raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
> ```
> 
> This all worked fine with expected output. Yes, while docker exec puts you in as root, I did change user to arm via 'su - arm' as that is what the main process runs as. 
> 
> ```
> MakeMKV disc number: 0
> Disk raw number: 0
> ```
> 
> I did note a few other things... not all of the imported py scripts have the correct permissions for execute:
> 
> root@arm:/opt/arm/arm/ripper# ls -la
> total 176
> drwxr-xr-x 1 arm  arm   4096 May 29 13:05 .
> drwxr-xr-x 1 arm  arm   4096 May 22 05:02 ..
> -rwxr-xr-x 1 arm  arm   7434 May 22 00:43 apprise_bulk.py
> -rw-r--r-- 1 arm  arm   3634 May 22 00:43 ARMInfo.py
> -rwxr-xr-x 1 arm  arm  10887 May 22 00:43 arm_ripper.py
> -rw-r--r-- 1 arm  arm  13745 May 22 00:43 handbrake.py
> -rwxr-xr-x 1 arm  arm  13513 May 22 00:43 identify.py
> -rwxr-xr-x 1 arm  arm    163 May 22 00:43 __init__.py
> -rwxr-xr-x 1 arm  arm   5131 May 22 00:43 logger.py
> -rw-r--r-- 1 arm  arm   9863 May 22 00:43 main.py
> -rw-r--r-- 1 arm  arm  16893 May 22 00:43 makemkv.py
> -rwxr-xr-x 1 arm  arm   9246 May 22 00:43 music_brainz.py
> -rw-r--r-- 1 arm  arm    555 May 22 00:43 ProcessHandler.py
> drwxr-xr-x 2 arm  arm   4096 May 22 05:02 __pycache__
> -rwxr-xr-x 1 arm arm   731 May 29 13:03 test.py
> -rwxr-xr-x 1 arm  arm  33567 May 22 00:43 utils.py
> 
> So, I corrected this by chmod 755 on the files here.
> 
> Additionally, there was a docker container update via apt in Ubuntu.
> 
> Testing again, things work!
> 
> So.... this issue is resolved for now. Initially I thought it was Apparmor flagging a subprocess task or something, but your project only needs to have mount permissions (I already outlined this in another post). So not sure if fixing permissions or the docker update fixed this issue.
> 
> I would however, at least update the code base so that these files have the correct executable bit set permissions.

What is the new container running? Kernel version?

**Comment by ghn8** [comment]
> I'm a special case, I'm running on TrueNAS, but that's also Docker. Now I see that your issue was slightly different. You got an actual error, for me, the `makemkvcon` command hangs indefinitely. This is the only error in `docker logs`, and that seems unrelated: `2025-05-29 22:35:18.671960+00:00tail: cannot open '/home/arm/logs/progress/18.log' for reading: No such file or directory`
> 
> I am able to rip CD's without issues though. ARM can also identify my diisc, so the devices and (I suspect) the permissions should be fine. Any idea?

I too am trying to get this to work on TrueNas. I am basically agreeing with the quoted about. 

Docker logs :

```
May 30 21:47:03 161c30a08058 ARM: [ARM] Entering docker wrapper
May 30 21:47:05 161c30a08058 ARM: [ARM] Starting ARM for DVD on sr0
[2025-05-30 21:47:30,439] INFO ARM: settings.check_hw_transcode_support NVENC supported!
[2025-05-30 21:47:30,440] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
[2025-05-30 21:47:36,290] INFO ARM: settings.check_hw_transcode_support NVENC supported!
[2025-05-30 21:47:36,290] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
[2025-05-30 21:48:09,908] INFO ARM: settings.check_hw_transcode_support NVENC supported!
[2025-05-30 21:48:09,909] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
tail: cannot open '/home/arm/logs/progress/10.log' for reading: No such file or directory
tail: cannot open '/home/arm/logs/progress/10.log' for reading: No such file or directory
tail: cannot open '/home/arm/logs/progress/10.log' for reading: No such file or directory
tail: cannot open '/home/arm/logs/progress/10.log' for reading: No such file or directory
May 30 21:47:05 161c30a08058 ARM: eject: device name is `/dev/sr0'
May 30 21:48:21 161c30a08058 ARM: eject: /dev/sr0: not mounted
May 30 21:48:21 161c30a08058 ARM: eject: /dev/sr0: is whole-disk device
May 30 21:48:21 161c30a08058 ARM: eject: /dev/sr0: trying to eject using SCSI commands
May 30 21:48:21 161c30a08058 ARM: eject: SCSI eject succeeded
May 30 21:48:22 161c30a08058 ARM: [ARM] Entering docker wrapper
May 30 21:48:22 161c30a08058 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
[2025-05-30 21:48:43,467] INFO ARM: settings.check_hw_transcode_support NVENC supported!

```
ARM logs:

```
05-30-2025 20:27:34] INFO ARM: Starting MakeMKV rip. Method is mkv
[05-30-2025 20:27:41] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[05-30-2025 20:27:41] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[05-30-2025 20:27:41] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 52, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 55, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 59, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 28, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 223, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 111, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 59, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[05-30-2025 20:27:41] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

I have the UI working and OMDB is pulling the proper info. If I leave the as `Rip Method: mkv` it fails in this manor above and open the drive. But if I change it to `Rip Method: backup` it will take the stage 1 of 2 of the transcode in about 15 mins at most but stage 2 of 2 takes like 8 hours. I am guessing this is a normal thing using the `Rip Method: backup` but wanted to add this as it might be important.

**Comment by ynnckvdv** [comment]
@ghn8 So if you select `Rip Method: backup` it works? Because for me the `makemkvcon -r info disc:9999` command still hangs. It's very strange behaviour.

Edit: forgot that backup only uses HandbrakeCLI and doesn't use MakeMKV at all. So not that strange. At this point I'm still not sure why MakeMKV won't start.

**Comment by ynnckvdv** [comment]
@polskikrol I have been able to rip CD and DVD just fine, so that should be alright. It's just Blu Ray that's acting up.

**Comment by ghn8** [comment]
> [@polskikrol](https://github.com/polskikrol) I have been able to rip CD and DVD just fine, so that should be alright. It's just Blu Ray that's acting up.

I am also on truenas but can not rip blurays or dvds with makemkv. Only the back up handbrake only method. But I do get the explicit error. `Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.` Now I would like to try @polskikrol's method of 

> So, I corrected this by chmod 755 on the files here.

But I can't even find this directory, as trunas structures things seemingly different as to try to make it easier not to screw things up. I am at a dead end but will keep trying.

**Comment by ynnckvdv** [comment]
> > [@polskikrol](https://github.com/polskikrol) I have been able to rip CD and DVD just fine, so that should be alright. It's just Blu Ray that's acting up.
> 
> I am also on truenas but can not rip blurays or dvds with makemkv. Only the back up handbrake only method. But I do get the explicit error. `Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.` Now I would like to try @polskikrol's method of 
> 
> > So, I corrected this by chmod 755 on the files here.
> 
> But I can't even find this directory, as trunas structures things seemingly different as to try to make it easier not to screw things up. I am at a dead end but will keep trying.  

If you go to TrueNAS' Shell, you can run `sudo docker exec -it NAME bash`. Or you can enter the Shell via Apps -> ARM-> there should be a button for the shell.

There the directory is under `/opt/arm/arm/ripper`.

**Comment by microtechno9000** [comment]
I have been trying to find info on what makemkvcon is doing at this point, the docs are rather limited. Found some old info in ARM, nice of the old devs to leave some breadcrumbs

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blame/5b557e42a1b0decb3711d38777799e05faa6e544/arm_wiki/MakeMKV-Codes.md#L130

The example in the wiki returns

`DRV:0,2,999,1,"DVD-ROM TEAC DVD-ROM DV28SV R.0C","WRATH_OF_THE_TITANS","/dev/sr0"`

ARM then parses that to get the drive ID, in this instance 0

For the code in `makemkv.py`, at the below line, can you modify the code within the docker container and re-run

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/5b557e42a1b0decb3711d38777799e05faa6e544/arm/ripper/makemkv.py#L49

From:

`cmd = f"makemkvcon -r info disc:9999 | grep {job.devpath} | grep -oP '(?<=:).*?(?=,)'"`

To:

`cmd = f"makemkvcon -r info dev:{job.devpath}  | grep {job.devpath} | grep -oP '(?<=:).*?(?=,)'"`

Let me know if that resolves the issue

**Comment by ghn8** [comment]
@ynnckvdv thanks for helping navigate truenas ux and helping me learn about docker more, it's a separate container.... makes total sense now. 

@polskikrol your solution 

> So, I corrected this by chmod 755 on the files here.

for the `opt/arm/arm/ripper` directory worked and now DVDs and CDs are working just fine. (At least it is working, I am still needing to confirm that Nvidia NVENC is working properly... I will check another day). 

@microtechno9000 I tried to switch to `cmd = f"makemkvcon -r info dev:{job.devpath}  | grep {job.devpath} | grep -oP '(?<=:).*?(?=,)'"` in file `makemkv.py` in directory `opt/arm/arm/ripper` and this is the new error only for bluray disks below. 

To confirm, I got this error on a bluray disk that I know can be ripped by makemkv on my windows machine. And I did install the latest version of ARM from the Truenas team.  There latest version is showing `App Version: v2.15.0 Version: v1.0.8`

Bluray only error now (I am in the camp now that blurays are my only issue):

```[06-05-2025 02:20:26] INFO ARM: Starting MakeMKV rip. Method is mkv
[06-05-2025 02:20:29] INFO ARM: MakeMKV disc number: 2024
[06-05-2025 02:20:29] INFO ARM: Destination is /home/arm/media/raw/Lone-Survivor
[06-05-2025 02:20:29] INFO ARM: Processing files to: /home/arm/media/raw/Lone-Survivor
[06-05-2025 02:20:29] INFO ARM: Using MakeMKV to get information on all the tracks on the disc. This will take a few minutes...
[06-05-2025 02:20:32] INFO ARM: Found 0 titles
[06-05-2025 02:20:33] INFO ARM: Trying to find mainfeature
[06-05-2025 02:20:33] INFO ARM: Processing track #0 as mainfeature. Length is 0 seconds.
[06-05-2025 02:20:33] INFO ARM: Ripping title 0 to /home/arm/media/raw/Lone-Survivor/
MSG:1005,0,1,"MakeMKV v1.18.1 linux(x64-release) started","%1 started","MakeMKV v1.18.1 linux(x64-release)"
MSG:5042,0,0,"The program can't find any usable optical drives.","The program can't find any usable optical drives."
DRV:0,256,999,0,"","",""
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:2024,16777216,1,"Unknown device - '/dev/sr2'","Unknown device - '%1'","/dev/sr2"
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
[06-05-2025 02:20:36] ERROR ARM: Call to MakeMKV failed with code: 11 (b'')
[06-05-2025 02:20:36] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException`

**Comment by polskikrol** [comment]
@microtechno9000 Ok, so looks like permissions should be fixed in the docker git image to resolve my original problem. Dont think the issue was the script snippet that determines the disc drive id.

@ynnckvdv Just to verify, are you able to rip DVDs without issue? Have you tried to run the MakeMKV commands manually inside of the container? (I usually perform all testing, validation, and tweaks by connecting via 'docker exec' and then changing to the arm user.) In terms of acceleration, these images dont usually include the needed libraries and need to be installed/compiled manually. I wrote a dockerfile which installs the requirements for older Intel QSV but have not tinkered with NVIDIA. The proper way would be for the docker image to include the various install scripts, like it does for MakeMKV and HandBrakeCLI, and by passing a HARDWARE environment variable, having docker init install the dependencies on first run.

**Comment by ynnckvdv** [comment]
@polskikrol I haven't changed the script yet, and I'm afraid I won't be able to for a few days. But no, I couldn't rip DVD with MakeMKV. Only with Handbrake.

**Comment by microtechno9000** [comment]
@polskikrol sounds like you have it working

If so we can close this issue as just being permissions related

**Comment by polskikrol** [comment]
Actually, no. I just pulled the newest docker image. The issue is in the actual docker image... not a user/environment problem. Once the permissions are fixed on the repo, then we can close this.

**Comment by bigcat** [comment]
Changing the permissions on the docker environment didn't fix it for me - I still can't rip bluray or DVD discs, and fail with the same error message.

**Comment by ghn8** [comment]
I have reinstalled and redone all of these steps. I recreated my findings from before. 

On truenas and using their version of ARM. 

I have corrected the `opt/arm/arm/ripper` permissions and replaced `cmd = f"makemkvcon -r info dev:{job.devpath}  | grep {job.devpath} | grep -oP '(?<=:).*?(?=,)'"` in `makemkv.py`

These are the scenario that function as expected.  

DVD - Rip method: MKV - Main Feature: true - drive mode: auto
DVD - Rip method: backup - Main Feature: true - drive mode: auto
All CD rips seem to work

These are the scenario that do not function as expected.  

Blurays do not rip in any form and DVDs do not work in manual mode or if main feature is false. 

These instances result in similar errors `Couldn't find a valid track` `found 0 titles` `Processing track #0 as mainfeature. Length is 0 seconds.` `MSG:5042,0,0,"The program can't find any usable optical drives.","The program can't find any usable optical drives."` `Failed to open disc`. 

But if I try to rip a DVD in auto mode it works just fine, so it can read the drive sometimes. 

Anything in manual mode just waits like it should but only has one track option to chose from and it shows 0 data. Blurays in auto or maunal mode and/or backup or mkv mode just simply do not rip. They get identified but just eject or in manual mode they have the same error showing one null track to chose from. 

I have 2 drive, one sata and one usb. Both result in same errors. 

If this is the wrong thread at this point, please let me know. I could not find error messages like the ones I described above and at least it seems to me that sometimes makemkv can read the drive at `/dev/sr0` and `/dev/sr1` but under some scenarios it just fails to read the drive. I hope this is helpful and pertinent to this issue. 

*Edited to confirm the scenario that it does work.

**Comment by hypeseverer** [comment]
> > [@polskikrol](https://github.com/polskikrol) I have been able to rip CD and DVD just fine, so that should be alright. It's just Blu Ray that's acting up.
> 
> I am also on truenas but can not rip blurays or dvds with makemkv. Only the back up handbrake only method. But I do get the explicit error. `Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.` Now I would like to try [@polskikrol](https://github.com/polskikrol)'s method of
> 
> > So, I corrected this by chmod 755 on the files here.
> 
> But I can't even find this directory, as trunas structures things seemingly different as to try to make it easier not to screw things up. I am at a dead end but will keep trying.

Following this PR as I am having the same issue after trying to load ARM on TrueNAS. 

Thought I would add to your question about the directory. Since (it sounds like) you also have ARM installed on TrueNAS through their App Catalog, you can also click on the container to bring up 'Details', scroll down to 'Workloads', then you'll see the containers that are running within this application. Clicking the folder icon next to each brings up their Volume Mounts. Showing their Sources and Destinations.

**Comment by malacandrian** [comment]
I'm another user running from the TrueNAS app catalog, experiencing what might be the same issue.

Issue #1405 (which was marked as a duplicate of this one) shows the mount failing before the MakeMKV failure. I am also seeing this mounting failure, but all the logs posted to this issue are abridged and don't show whether or not mounting succeeded.

```
[05-30-2025 15:09:05] INFO ARM: Starting Disc identification
[05-30-2025 15:09:05] INFO ARM: Mounting disc to: /mnt/dev/sr0
[05-30-2025 15:09:05] ERROR ARM: Mounting failed! Rip might have problems
```

One of the causes of the mounting failure was that TrueNAS didn't give the SYSADMIN capability to their container, so it was unable to use the mount command. This was fixed in [PR 2554](https://github.com/truenas/apps/pull/2554). Even with that change applied my installation is failing at the mounting step. Attempting to mount manually returns the following error:

```bash
> mount /dev/sr0 /mnt/dev/sr0
mount: /mnt/dev/s0: cannot mount /dev/sr0 read only
```

The drive can be mounted to the TrueNAS host without any issues.

Is this what the rest of you are seeing, or do I need to open a different issue?

**Comment by compilingEntropy** [comment]
I'm also experiencing the same issue @malacandrian — TrueNAS app catalog user.

Mount failed in logs:
```
[2025-06-20_16:52:19] INFO ARM: Starting Disc identification
[2025-06-20_16:52:19] INFO ARM: Mounting disc to: /mnt/dev/sr0
[2025-06-20_16:52:19] ERROR ARM: Mounting failed! Rip might have problems
```

Unable to mount manually:
```
root@0048b53a19f5:~# mount /dev/sr0 /mnt/dev/sr0
mount: /mnt/dev/sr0: cannot mount /dev/sr0 read-only.
```
After reading identify.py, it seems this is the exact command it runs to attempt the mount (which fails with the same error):
```
root@0048b53a19f5:~# mount /mnt/dev/sr0
mount: /mnt/dev/sr0: cannot mount /dev/sr0 read-only.
```

Later down in the logs I'm seeing the same error as other people, but for me at least this seems more of a symptom than the issue itself. I can reproduce the failure with `makemkvcon` as well.
```
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.
```
```
root@0048b53a19f5:~# makemkvcon -r info disc:9999
MSG:1005,0,1,"MakeMKV v1.18.1 linux(x64-release) started","%1 started","MakeMKV v1.18.1 linux(x64-release)"
MSG:5042,0,0,"The program can't find any usable optical drives.","The program can't find any usable optical drives."
DRV:0,256,999,0,"","",""
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
TCOUNT:0
```

I tried `chmod 755 /opt/arm/arm/ripper/*.py` to no effect, and I also can mount the drive to the TrueNAS host with no issues.

**Comment by ScotchTape** [comment]
I just stumbled over this while kicking the idea around to install it on a seperate proxmox host, instead on TrueNAS Scale on my ugreen.
Anyway. I installed ARM yesterday from the packaged TrueNAS Apps and couldn't get it to work either. While poking around I found in another repo, I think it's mentioned in the QSV-bug, but he also had the /dev/sg? added. 
I added `/dev/sg4` as `/dev/sg4` (replace it with your `lsscsi -g` output) to my Container, opened a shell and makemkvcon was able to finally see the disk a started ripping away.

**Comment by rclough158** [comment]
I'm running on TrueNas Scale with a custom docker compose file and was seeing the same issues as in this thread. CDs ripped fine, but DVD and Blue-Ray (which need makeMKV) were locked up in starting steps.
It's not the ideal solution, but downgrading **my arm installation to 2.8.0** and deleting the arm.db file has enabled me to rip video formats. I'd guess its an older version of makeMKV that's making this possible as a **temporary** solution.
Attaching an image of my compose file for reference (perma-key blacked out).

![Image](https://github.com/user-attachments/assets/8f0bc60f-eaac-449a-9db5-1bf2f9990647)

**Comment by malacandrian** [comment]
> I just stumbled over this while kicking the idea around to install it on a seperate proxmox host, instead on TrueNAS Scale on my ugreen. Anyway. I installed ARM yesterday from the packaged TrueNAS Apps and couldn't get it to work either. While poking around I found in another repo, I think it's mentioned in the QSV-bug, but he also had the /dev/sg? added. I added `/dev/sg4` as `/dev/sg4` (replace it with your `lsscsi -g` output) to my Container, opened a shell and makemkvcon was able to finally see the disk a started ripping away.

Adding the sgx device also appears to have worked for me. ~It has yet to complete the first rip, but it has at least gotten further than ever before~. Update: The entire rip process worked perfectly.

Bizzarely; the ARM logs still claim that the mount failed, `/proc/mounts` does not contain any record of the mount, and trying to mount manually does not work; but ARM is happy to rip the disk anyway.
