### ISSUE TITLE
🐛 MakeMKV failing on all DVDs and BluRays with Code:1

### ISSUE THREAD

**Issue by Bigjohn4** [automatic-ripping-machine/automatic-ripping-machine#1432]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### I have checked the wiki

- [x] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [x] I'm using the latest release

### Describe the bug?

I used ARM to rip more that 100 DVDs and Blu-Rays of several weeks. I then took a two week brake. When I again tried to rip a DVD, it failed. I tried 6 or so DVDs and Blu-rays. All failed. So, I then installed newest MakeMKV 1.18.1, following instructions here:
https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224
following install and reboot, I tried again. Still failed as before.

### To Reproduce

All tries fail on both of  my CDROM and BluRay drives.

### What OS are you seeing the problem on?

ubuntu-24.02

### ARM Release Version or Git hash (You can find this in the arm settings page)

Python version: 3.10.12
A.R.M version: 2.13.0
Current git version: 1b85f51

### Expected behavior?

I expect rip to work like it was doing.

### Relevant log output

```shell
Loading log: TRIFFIDS.log...

[06-25-2025 21:41:30] INFO ARM: ARM version: 2.13.0
[06-25-2025 21:41:30] INFO ARM: Python version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
[06-25-2025 21:41:30] INFO ARM: User is: arm
[06-25-2025 21:41:30] INFO ARM: Alembic head is: 6870a5546912
[06-25-2025 21:41:30] INFO ARM: Database version is: 6870a5546912
[06-25-2025 21:41:30] INFO ARM: ************* Starting ARM processing at 2025-06-25 21:41:30.180653 *************
[06-25-2025 21:41:31] INFO ARM: Looking for log files older than 1 days old.
[06-25-2025 21:41:31] INFO ARM: Checking path /home/arm/logs/ for old log files...
[06-25-2025 21:41:31] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[06-25-2025 21:41:31] INFO ARM: Job: TRIFFIDS
[06-25-2025 21:41:31] INFO ARM: Job #124 with PID 2586 is currently running.
[06-25-2025 21:41:31] INFO ARM: Starting Disc identification
[06-25-2025 21:41:31] INFO ARM: Mounting disc to: /mnt/dev/sr0
[06-25-2025 21:41:32] INFO ARM: Mounting disc was successful
[06-25-2025 21:41:32] INFO ARM: Disc identified as video
[06-25-2025 21:41:32] INFO ARM: DVD CRC64 hash is: 09f17e270361073c
[06-25-2025 21:41:32] INFO ARM: Disc title Post ident -  title:The-Day-of-the-Triffids year:1963 video_type:movie disctype: dvd
[06-25-2025 21:41:32] INFO ARM: We have no previous rips/jobs matching this label
[06-25-2025 21:41:33] INFO ARM: Waiting 60 seconds for manual override.
[06-25-2025 21:42:33] INFO ARM: ******************* Logging ARM variables *******************
[06-25-2025 21:42:33] INFO ARM: devpath: /dev/sr0
[06-25-2025 21:42:33] INFO ARM: mountpoint: /mnt/dev/sr0
[06-25-2025 21:42:33] INFO ARM: title: The-Day-of-the-Triffids
[06-25-2025 21:42:33] INFO ARM: year: 1963
[06-25-2025 21:42:33] INFO ARM: video_type: movie
[06-25-2025 21:42:33] INFO ARM: hasnicetitle: True
[06-25-2025 21:42:33] INFO ARM: label: TRIFFIDS
[06-25-2025 21:42:33] INFO ARM: disctype: dvd
[06-25-2025 21:42:33] INFO ARM: manual_start: False
[06-25-2025 21:42:33] INFO ARM: ******************* End of ARM variables *******************
[06-25-2025 21:42:33] INFO ARM: ******************* Logging config parameters *******************
[06-25-2025 21:42:33] INFO ARM: skip_transcode: False
[06-25-2025 21:42:33] INFO ARM: mainfeature: False
[06-25-2025 21:42:33] INFO ARM: minlength: 600
[06-25-2025 21:42:33] INFO ARM: maxlength: 99999
[06-25-2025 21:42:33] INFO ARM: videotype: auto
[06-25-2025 21:42:33] INFO ARM: manual_wait: True
[06-25-2025 21:42:33] INFO ARM: manual_wait_time: 60
[06-25-2025 21:42:33] INFO ARM: ripmethod: mkv
[06-25-2025 21:42:33] INFO ARM: mkv_args: 
[06-25-2025 21:42:33] INFO ARM: delrawfiles: True
[06-25-2025 21:42:33] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[06-25-2025 21:42:33] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[06-25-2025 21:42:33] INFO ARM: hb_args_dvd: --subtitle scan -F
[06-25-2025 21:42:33] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[06-25-2025 21:42:33] INFO ARM: raw_path: /home/arm/media/raw/
[06-25-2025 21:42:33] INFO ARM: transcode_path: /home/arm/media/transcode/
[06-25-2025 21:42:33] INFO ARM: completed_path: /home/arm/media/completed/
[06-25-2025 21:42:33] INFO ARM: extras_sub: extras
[06-25-2025 21:42:33] INFO ARM: emby_refresh: False
[06-25-2025 21:42:33] INFO ARM: emby_server: 
[06-25-2025 21:42:33] INFO ARM: emby_port: 8096
[06-25-2025 21:42:33] INFO ARM: notify_rip: True
[06-25-2025 21:42:33] INFO ARM: notify_transcode: True
[06-25-2025 21:42:33] INFO ARM: max_concurrent_transcodes: 0
[06-25-2025 21:42:33] INFO ARM: ******************* End of config parameters *******************
[06-25-2025 21:42:33] INFO ARM: Checking for fstab entry.
[06-25-2025 21:42:33] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[06-25-2025 21:42:33] INFO ARM: Final Output directory "/home/arm/media/transcode/movies/The-Day-of-the-Triffids (1963)"
[06-25-2025 21:42:33] INFO ARM: Final Output directory "/home/arm/media/completed/movies/The-Day-of-the-Triffids (1963)"
[06-25-2025 21:42:33] INFO ARM: Processing files to: /home/arm/media/transcode/movies/The-Day-of-the-Triffids (1963)
[06-25-2025 21:42:33] INFO ARM: ************* Ripping disc with MakeMKV *************
[06-25-2025 21:42:33] INFO ARM: Job running in auto mode
[06-25-2025 21:42:33] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-iyhMMBV8nWtNo3BgMdcvypH8UL01nYmww2zFzQDtiZsdJUOaAuCURsPRQ1Hj3i75RE
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[06-25-2025 21:42:34] INFO ARM: Starting MakeMKV rip. Method is mkv
[06-25-2025 21:42:34] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[06-25-2025 21:42:34] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[06-25-2025 21:42:34] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 52, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 55, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 59, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 28, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 223, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 111, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 59, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[06-25-2025 21:42:34] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.

Automatic Ripping Machine. Find us on github.
```

### Anything else?

Do i need to update something else?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Bigjohn4** [comment]
went trough same process with DEBUG set. Here is that log.

[TRIFFIDS_175103960259.log](https://github.com/user-attachments/files/20951970/TRIFFIDS_175103960259.log)

**Comment by dablenparty** [comment]
Also experiencing this on CachyOS (Arch Linux derivative) with Python version: 3.10.12, A.R.M version: 2.15.1, and git version: `abcacb6`

Edit: I fixed this on my machine by running `sudo modprobe sg`, which I got from [this MakeMKV forum thread](https://forum.makemkv.com/forum/viewtopic.php?t=23759)
Edit 2: after doing that, my git version is now `8ae2fae` for some reason

**Comment by microtechno9000** [comment]
The git version would be due to the bugfix pushed last week, ARM updated if you pulled a new docker image

**Comment by microtechno9000** [comment]
Closing as resolved by running `sudo modprobe sg`

**Comment by Bigjohn4** [comment]
I had already tried a reboot, which did not fix the problem. I did, try the command mentioned in above post   sudo modprobe sg
Still fails. I have installed latest version of makemkv 1.18.1, both bin and oss. Did not fix issue.
 Does something else need updating?

**Comment by dablenparty** [comment]
@microtechno9000 also gotta restart the container after running that

**Comment by Bigjohn4** [comment]
My problem is not fixed. ARM worked for several weeks processing 130 or so
disks. Then, after a two week gap, no longer working. I did no updates
between the time it worked and when it failed. Might have had some
automatic updates, I don't know how to tell.


JM

**Comment by dablenparty** [comment]
Alright then. @microtechno9000, that command is _not_ a solution, but a temporary bandaid that goes away after a reboot. I linked the forum post that explains this, but apparently you did not want to take the time to read that. @Bigjohn4, you have two options based on that post:

## Load `sg` module at boot (**recommended**)

```shell
# change user to root because sudo does not work for this
su root
# create the necessary directory
mkdir -vp /etc/modules-load.d
# add the kernel module
echo sg > /etc/modules-load.d/sg.conf
# logout of root
exit
# restart system
reboot
```

## `modprobe` command

**IMPORTANT!**: This method does not persist through reboots. If you want/need that, use the other method.

Simply run the following:

```shell
sudo modprobe sg
```

Afterwards, you'll have to restart the ARM service, whether it's a Docker container or system unit.

If you're still having problems after this, I can't help you.

**Comment by microtechno9000** [comment]
> Alright then. @microtechno9000, that command is _not_ a solution, but a temporary bandaid that goes away after a reboot. I linked the forum post that explains this, but apparently you did not want to take the time to read that. @Bigjohn4, you have two options based on that post:
> 
> ## Load `sg` module at boot (**recommended**)
> 
> ```shell
> # change user to root because sudo does not work for this
> su root
> # create the necessary directory
> mkdir -vp /etc/modules-load.d
> # add the kernel module
> echo sg > /etc/modules-load.d/sg.conf
> # logout of root
> exit
> # restart system
> reboot
> ```
> 
> ## `modprobe` command
> 
> **IMPORTANT!**: This method does not persist through reboots. If you want/need that, use the other method.
> 
> Simply run the following:
> 
> ```shell
> sudo modprobe sg
> ```
> 
> Afterwards, you'll have to restart the ARM service, whether it's a Docker container or system unit.
> 
> If you're still having problems after this, I can't help you.
> 

sorry dude
Lot going on, the dev team is pretty much just me at the moment. Doing what I can to keep ARM going

Are you able to modify the docker build script, rebuild ARM locally and confirm the fix.

that is running the modprobe fix you commented on above?

edit: I can try on my dev machine, but haven't run into this issue so won't be able to test it

**Comment by dablenparty** [comment]
There should be no need to modify the Docker build script or rebuild ARM at all because this has nothing to do with Docker or how ARM is compiled, it's about the system ARM is running on and whether or not that system runs Linux and has the `sg` module loaded into its kernel. You can check that with `lsmod`. If the outputted list has the `sg` module, it's loaded; if not, you need to load it with one of the solutions I outlined above. Both solutions are done in a terminal on the machine ARM is running on, _not_ inside the ARM container. Running `modprobe` inside the container doesn't even work.

After enabling the module, either with `sudo modprobe sg` or the `conf` file, the ARM service must be _restarted_, not rebuilt. For Docker,  it's as simple as `docker compose down && docker compose up -d` (`docker compose restart` did not work for me).

P.S. if you want to disable the `sg` module for testing, try `sudo modprobe -r sg`. It should disable the module until you re-enable it, either manually or with a reboot (if that is setup).

**Comment by Bigjohn4** [comment]
Thanks for your explanation.   I'll give it a try next week when I get back
home.

Happy 4th of July 😄


JM

**Comment by microtechno9000** [comment]
> There should be no need to modify the Docker build script or rebuild ARM at all because this has nothing to do with Docker or how ARM is compiled, it's about the system ARM is running on and whether or not that system runs Linux and has the `sg` module loaded into its kernel. You can check that with `lsmod`. If the outputted list has the `sg` module, it's loaded; if not, you need to load it with one of the solutions I outlined above. Both solutions are done in a terminal on the machine ARM is running on, _not_ inside the ARM container. Running `modprobe` inside the container doesn't even work.
> 
> After enabling the module, either with `sudo modprobe sg` or the `conf` file, the ARM service must be _restarted_, not rebuilt. For Docker, it's as simple as `docker compose down && docker compose up -d` (`docker compose restart` did not work for me).
> 
> P.S. if you want to disable the `sg` module for testing, try `sudo modprobe -r sg`. It should disable the module until you re-enable it, either manually or with a reboot (if that is setup).

Thanks for the info

Seems that whilst the host system is similar Ubuntu 24.04.2 LTS, kernel 6.8.0-63-generic, I have not run into issues, and the `sg` module is not loaded.

@Bigjohn4 are you running as privileged?
```bash
    --privileged \
```

**Comment by microtechno9000** [comment]
Noting, issue is related to #1417

**Comment by Bluscream** [comment]
How am u supposed to run the modprobe in a (UNRAID) docker container? Do i have to do it in the host or in the container shell? or do i have to add something in the docker config?

![](https://files.catbox.moe/yc5ays.png)

when i try it in the container i get
```bash
root@78504cc5e4c6:/home/arm# uname -a
Linux 78504cc5e4c6 6.12.24-Unraid #1 SMP PREEMPT_DYNAMIC Sat May  3 00:12:52 PDT 2025 x86_64 x86_64 x86_64 GNU/Linux
root@78504cc5e4c6:/home/arm# lsb_release
No LSB modules are available.
root@3f9d8e408d92:/home/arm# modprobe sg
bash: modprobe: command not found
root@78504cc5e4c6:/home/arm# apt-get install kmod
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package kmod
root@78504cc5e4c6:/home/arm# depmod
bash: depmod: command not found
```

**Comment by Bigjohn4** [comment]
I have done the procedure outlined above using the creating the /etc/modules-load.d directory and sg.conf file. I then rebooted. lsmod does not show an sg module running.

The other  question, yes, I have the --privileged \

here is my start script:
docker run -d \
      -p "8080:8080" \
      -e ARM_UID="1001" \
      -e ARM_GID="1001" \
      -e TZ="Chicago"  \
    -v "/arm:/home/arm" \
    -v "/arm/music:/home/arm/music" \
    -v "/arm/logs:/home/arm/logs" \
    -v "/arm/media:/home/arm/media" \
    -v "/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="dev/sr1:/dev/sr1" \
    --privileged \
    --restart "always"  \
    --name "arm-rippers"  \
    --cpuset-cpus='4,5,6,7,8,9,10,11,12,13,14,15'  \
    automaticrippingmachine/automatic-ripping-machine:latest**

I have not tried the docker compose command, since the sg module is not showing up.

Does Ubuntu use some other module instead of sg?

Thanks for all you guys time. I am lost. Why would it work for weeks, and then stop. I changed nothing. Had to be an automatic update of some sort.

**Comment by Bigjohn4** [comment]
One more thing. Ubuntu most have something loaded instead of sg, since it sees the DVD drives and uses them. Its MakeMKV that is having an issue. If you look at the log I uploaded, you can see the drive being used. Got to be an issue with MakeMKV. 

Here is lsmod output. This is after I did the conf file

john@ARM:~$ sudo lsmod
Module                  Size  Used by
tls                   155648  0
udf                   151552  0
crc_itu_t              12288  1 udf
xt_mark                12288  3
nf_conntrack_netlink    57344  0
xt_nat                 12288  7
xt_tcpudp              16384  1
veth                   45056  0
snd_seq_dummy          12288  0
snd_hrtimer            12288  1
xt_conntrack           12288  17
xt_MASQUERADE          16384  1
bridge                421888  0
stp                    12288  1 bridge
llc                    16384  2 bridge,stp
xt_set                 20480  0
ip_set                 61440  1 xt_set
nft_chain_nat          12288  7
nf_nat                 61440  3 xt_nat,nft_chain_nat,xt_MASQUERADE
nf_conntrack          200704  5 xt_conntrack,nf_nat,xt_nat,nf_conntrack_netlink,                            xt_MASQUERADE
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         12288  1 nf_conntrack
xt_addrtype            12288  4
nft_compat             20480  33
nf_tables             385024  391 nft_compat,nft_chain_nat
libcrc32c              12288  3 nf_conntrack,nf_nat,nf_tables
xfrm_user              65536  1
xfrm_algo              16384  1 xfrm_user
cmac                   12288  1
nls_utf8               12288  90
cifs                 1499136  2
cifs_arc4              12288  1 cifs
nls_ucs2_utils          8192  1 cifs
cifs_md4               12288  1 cifs
netfs                 557056  1 cifs
overlay               212992  2
qrtr                   53248  2
binfmt_misc            24576  1
nls_iso8859_1          12288  1
snd_sof_pci_intel_tgl    12288  0
intel_rapl_msr         20480  0
snd_sof_pci_intel_cnl    20480  1 snd_sof_pci_intel_tgl
intel_rapl_common      53248  1 intel_rapl_msr
snd_sof_intel_hda_generic    36864  2 snd_sof_pci_intel_tgl,snd_sof_pci_intel_cn                            l
intel_uncore_frequency    12288  0
soundwire_intel        77824  1 snd_sof_intel_hda_generic
intel_uncore_frequency_common    16384  1 intel_uncore_frequency
soundwire_cadence      45056  1 soundwire_intel
snd_sof_intel_hda_common   184320  3 snd_sof_intel_hda_generic,snd_sof_pci_intel                            _tgl,snd_sof_pci_intel_cnl
snd_sof_intel_hda_mlink    45056  3 soundwire_intel,snd_sof_intel_hda_common,snd                            _sof_intel_hda_generic
snd_sof_intel_hda      24576  2 snd_sof_intel_hda_common,snd_sof_intel_hda_gener                            ic
snd_sof_pci            24576  3 snd_sof_intel_hda_generic,snd_sof_pci_intel_tgl,                            snd_sof_pci_intel_cnl
snd_sof_xtensa_dsp     12288  1 snd_sof_intel_hda_generic
snd_sof               385024  5 snd_sof_pci,snd_sof_intel_hda_common,snd_sof_int                            el_hda_generic,snd_sof_intel_hda,snd_sof_pci_intel_cnl
snd_sof_utils          16384  1 snd_sof
snd_soc_hdac_hda       24576  1 snd_sof_intel_hda_common
snd_soc_acpi_intel_match   114688  3 snd_sof_intel_hda_generic,snd_sof_pci_intel                            _tgl,snd_sof_pci_intel_cnl
soundwire_generic_allocation    12288  1 soundwire_intel
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_sof_intel_hda_gener                            ic
soundwire_bus         122880  3 soundwire_intel,soundwire_generic_allocation,sou                            ndwire_cadence
snd_soc_avs           200704  0
snd_hda_codec_realtek   212992  1
snd_soc_hda_codec      24576  1 snd_soc_avs
snd_hda_codec_generic   122880  1 snd_hda_codec_realtek
snd_hda_ext_core       32768  6 snd_soc_avs,snd_soc_hda_codec,snd_sof_intel_hda_                            common,snd_soc_hdac_hda,snd_sof_intel_hda_mlink,snd_sof_intel_hda
snd_hda_scodec_component    20480  1 snd_hda_codec_realtek
snd_soc_core          434176  6 snd_soc_avs,snd_soc_hda_codec,soundwire_intel,sn                            d_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda
x86_pkg_temp_thermal    20480  0
snd_hda_codec_hdmi     98304  1
intel_powerclamp       24576  0
snd_compress           28672  2 snd_soc_avs,snd_soc_core
ac97_bus               12288  1 snd_soc_core
sch_fq_codel           24576  6
snd_pcm_dmaengine      16384  1 snd_soc_core
kvm_intel             487424  0
snd_hda_intel          61440  2
snd_intel_dspcfg       45056  5 snd_soc_avs,snd_hda_intel,snd_sof,snd_sof_intel_                            hda_common,snd_sof_intel_hda_generic
snd_intel_sdw_acpi     16384  2 snd_intel_dspcfg,snd_sof_intel_hda_generic
snd_usb_audio         540672  1
snd_hda_codec         204800  8 snd_hda_codec_generic,snd_soc_avs,snd_hda_codec_                            hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_codec_realtek,snd_soc_hdac_hda,snd_                            sof_intel_hda
kvm                  1421312  1 kvm_intel
snd_hda_core          143360  11 snd_hda_codec_generic,snd_soc_avs,snd_hda_codec                            _hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_hda_cod                            ec_realtek,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_usbmidi_lib        53248  1 snd_usb_audio
snd_hwdep              20480  2 snd_usb_audio,snd_hda_codec
snd_ump                45056  1 snd_usb_audio
snd_seq_midi           24576  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            57344  3 snd_seq_midi,snd_usbmidi_lib,snd_ump
mc                     81920  1 snd_usb_audio
cmdlinepart            16384  0
crct10dif_pclmul       12288  1
polyval_clmulni        12288  0
polyval_generic        12288  1 polyval_clmulni
spi_nor               163840  0
ghash_clmulni_intel    16384  0
snd_seq               122880  9 snd_seq_midi,snd_seq_midi_event,snd_seq_dummy
sha256_ssse3           32768  1
snd_pcm               196608  13 snd_soc_avs,snd_hda_codec_hdmi,snd_hda_intel,sn                            d_usb_audio,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_c                            ompress,snd_soc_core,snd_sof_utils,snd_hda_core,snd_pcm_dmaengine
sha1_ssse3             32768  0
ee1004                 16384  0
mtd                    98304  3 spi_nor,cmdlinepart
aesni_intel           122880  1
snd_seq_device         16384  4 snd_seq,snd_seq_midi,snd_ump,snd_rawmidi
crypto_simd            16384  1 aesni_intel
intel_pmc_core        118784  0
snd_timer              49152  3 snd_seq,snd_hrtimer,snd_pcm
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
i2c_i801               36864  0
coretemp               24576  0
snd                   143360  25 snd_hda_codec_generic,snd_seq,snd_seq_device,sn                            d_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_usb_audio,snd_usbmidi_lib,snd_hda_c                            odec,snd_hda_codec_realtek,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_ump,s                            nd_pcm,snd_rawmidi
intel_vsec             20480  1 intel_pmc_core
rapl                   20480  0
pmt_telemetry          16384  1 intel_pmc_core
i2c_mux                16384  1 i2c_i801
spi_intel_pci          12288  0
soundcore              16384  1 snd
intel_cstate           24576  0
wmi_bmof               12288  0
gigabyte_wmi           12288  0
spi_intel              32768  1 spi_intel_pci
i2c_smbus              16384  1 i2c_i801
msr                    12288  0
pmt_class              16384  1 pmt_telemetry
intel_hid              28672  0
mei_me                 53248  0
acpi_pad              184320  0
sparse_keymap          12288  1 intel_hid
acpi_tad               20480  0
mei                   172032  1 mei_me
mac_hid                12288  0
parport_pc             53248  1
ppdev                  24576  0
lp                     28672  0
parport                73728  3 parport_pc,lp,ppdev
efi_pstore             12288  0
nfnetlink              20480  7 nft_compat,nf_conntrack_netlink,nf_tables,ip_set
dmi_sysfs              24576  0
ip_tables              32768  0
x_tables               65536  9 xt_conntrack,nft_compat,xt_tcpudp,xt_addrtype,xt                            _nat,xt_set,ip_tables,xt_MASQUERADE,xt_mark
autofs4                57344  2
hid_generic            12288  0
usbhid                 77824  0
hid                   262144  2 usbhid,hid_generic
amdgpu              19730432  1
amddrm_ttm_helper      12288  1 amdgpu
amdttm                114688  2 amdgpu,amddrm_ttm_helper
amddrm_buddy           24576  1 amdgpu
amdxcp                 12288  1 amdgpu
drm_exec               12288  1 amdgpu
drm_suballoc_helper    20480  1 amdgpu
amd_sched              61440  1 amdgpu
amdkcl                 32768  3 amd_sched,amdttm,amdgpu
drm_display_helper    278528  1 amdgpu
nvme                   61440  1
cec                    94208  2 drm_display_helper,amdgpu
rc_core                73728  1 cec
crc32_pclmul           12288  0
r8169                 118784  0
nvme_core             221184  2 nvme
i2c_algo_bit           16384  1 amdgpu
ahci                   49152  3
intel_lpss_pci         28672  0
drm_ttm_helper         16384  1 amdgpu
intel_lpss             12288  1 intel_lpss_pci
xhci_pci               24576  0
libahci                53248  1 ahci
realtek                45056  1
ttm                   110592  1 drm_ttm_helper
nvme_auth              28672  1 nvme_core
idma64                 20480  0
xhci_pci_renesas       20480  1 xhci_pci
video                  77824  1 amdgpu
wmi                    28672  3 video,gigabyte_wmi,wmi_bmof
pinctrl_alderlake      32768  0
john@ARM:~$

**Comment by Bigjohn4** [comment]
This is not fixed. Why is it closed? do I need to start a new issue??


JM

**Comment by dablenparty** [comment]
@Bigjohn4 Ubuntu should have the `sg` kernel module because it's been part of the Linux kernel since the late 1990's. What happened when you tried the command `sudo modprobe sg`? `modprobe` usually only outputs errors, so if it outputted nothing, it probably worked. **Again, this command only temporarily loads the module until the next reboot.** If it didn't work, I honestly don't know. I said before I can't help you if the `sg` module doesn't work and I still stand by that. I simply don't have enough low-level knowledge. A quick web search took me to [this forum](https://askubuntu.com/questions/463644/why-is-a-scsi-disk-not-showing-up), which may or may not help. I use Arch, not Ubuntu, and I stopped using this project altogether recently so I'm not really that invested anymore either. There's a lot of design decisions that are just strange to me, like using `HandBrakeCLI` instead of `ffmpeg`, or worse, automatically down-mixing all audio to stereo by default (had to re-rip EVERYTHING because of this). The final straw for me is how the author is handling this issue, just closing it multiple times without checking with you to see if it's really fixed. 

@microtechno9000, I am now talking directly to you. I understand that life is busy and you are doing the majority of the work. I REALLY appreciate the effort you are putting into this project, as do many others. However, you are releasing this project publicly. Being busy is not an excuse to close issues without properly checking if the solution works or not, _especially_ when I was wrong and my suggestion didn't even work for OP. I'm a random person on the internet, you shouldn't trust me and just take what I say as the solution, that's why I linked the forum post and explained myself more. If you are spread too thin and don't have the time for this right now, that's understandable, but you need to communicate that. What's not understandable is closing issues that are not resolved as you have been doing with this one.

**Comment by Bluscream** [comment]
it didnt trickle downstream enough for me to test, sadly

**Comment by microtechno9000** [comment]
All

The issue was closed because I tagged it against a PR that was merged yesterday, so GitHub automatically closes the associated issue.

Based on the work that ukos-git did with the PR, I was hoping that these issues would be resolved as the makemkv calls were modified

If all those affect by this issue could confirm the issue still remains post 2.17.x, I can take a look into why

**Comment by wgarrity-1** [comment]
Not part of the original issue but I am still running into a similar issue even after upgrading to 2.17.x. ARM will find the disk, but then will freeze after starting MakeMKV. When I shell into the docker container and try to run any makemkvcon commands it also freezes.

It seems this might be a MakeMKV issue based on this forum post: https://forum.makemkv.com/forum/viewtopic.php?f=3&t=37670

Rolling back to ARM 2.9.0 which uses an older version of MakeMKV has not given me the same issue and I am able to rip DVDs and Blu-Rays with no issues (abet using an older version of ARM).

I would try to install an older version of MakeMKV (2.9.0 uses v1.17.8) in the 2.17.x Docker container, which might resolve the issue, but Docker is outside of my wheelhouse so I don't know where I would start with that.

```[07-12-2025 10:54:50] INFO ARM: ******************* Logging config parameters *******************
[07-12-2025 10:54:50] INFO ARM: skip_transcode: False
[07-12-2025 10:54:50] INFO ARM: mainfeature: False
[07-12-2025 10:54:50] INFO ARM: minlength: 600
[07-12-2025 10:54:50] INFO ARM: maxlength: 6000
[07-12-2025 10:54:50] INFO ARM: videotype: auto
[07-12-2025 10:54:50] INFO ARM: manual_wait: True
[07-12-2025 10:54:50] INFO ARM: manual_wait_time: 180
[07-12-2025 10:54:50] INFO ARM: ripmethod: mkv
[07-12-2025 10:54:50] INFO ARM: mkv_args: 
[07-12-2025 10:54:50] INFO ARM: delrawfiles: True
[07-12-2025 10:54:50] INFO ARM: hb_preset_dvd: H.265 NVENC 1080p
[07-12-2025 10:54:50] INFO ARM: hb_preset_bd: H.265 NVENC 2160p 4K
[07-12-2025 10:54:50] INFO ARM: hb_args_dvd: --subtitle scan -F
[07-12-2025 10:54:50] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[07-12-2025 10:54:50] INFO ARM: raw_path: /home/arm/media/raw/
[07-12-2025 10:54:50] INFO ARM: transcode_path: /home/arm/media/transcode/
[07-12-2025 10:54:50] INFO ARM: completed_path: /home/arm/media/completed/
[07-12-2025 10:54:50] INFO ARM: extras_sub: extras
[07-12-2025 10:54:50] INFO ARM: emby_refresh: False
[07-12-2025 10:54:50] INFO ARM: emby_server: 
[07-12-2025 10:54:50] INFO ARM: emby_port: 8096
[07-12-2025 10:54:50] INFO ARM: notify_rip: True
[07-12-2025 10:54:50] INFO ARM: notify_transcode: True
[07-12-2025 10:54:50] INFO ARM: max_concurrent_transcodes: 0
[07-12-2025 10:54:50] INFO ARM: max_concurrent_makemkvinfo: 0
[07-12-2025 10:54:50] INFO ARM: ******************* End of config parameters *******************
[07-12-2025 10:54:50] INFO ARM: Checking for fstab entry.
[07-12-2025 10:54:50] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[07-12-2025 10:54:50] INFO ARM: Final Output directory "/home/arm/media/transcode/unidentified/SBSP_THE_PILOT_A_MINI_MOVIE (2015)"
[07-12-2025 10:54:50] INFO ARM: Final Output directory "/home/arm/media/completed/unidentified/SBSP_THE_PILOT_A_MINI_MOVIE (2015)"
[07-12-2025 10:54:50] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/SBSP_THE_PILOT_A_MINI_MOVIE (2015)
[07-12-2025 10:54:50] INFO ARM: ************* Ripping disc with MakeMKV *************
[07-12-2025 10:54:51] INFO ARM: Updating MakeMKV key...
[07-12-2025 10:54:51] INFO ARM: Starting MakeMKV rip. Method is mkv```

**Comment by Bigjohn4** [comment]
I don't think the issue is with ARM but with MakeMKV. All was working until
my BetaKey expired and I upgraded MakeMKV to latest version. I am going to
look for a way to run previous version without having to pay $60 to try it.
Thanks for all your time and effort. I'll update as soon as I am able to
test again. Likely a week or so. Other projects get in the way 😀


JM

**Comment by Bigjohn4** [comment]
I have not heard from anyone on MakeMKV forum with an answer. 
Any more ideas here? I truly don't want to just start over or give up. Must be a fix of some sort.

**Comment by Bigjohn4** [comment]
Never got any ideas, so I decided to update Automatic Ripping Machine (ARM). 
I clicked on the "Update Available" link and let it update. 
Then put in a DVD and let it run. It did not run long before system crashed. On reboot, Ubuntu got a kernel panic and would not start. I tried recovery options, but no luck. So I reinstalled Ubuntu, Docker and ARM. Fortunately my config files were all on another file system so Arm started back up okay. I then put in DVD, and everything is working again. I have processed several DVDs and all seems to be working again. 

A bit brute force, but it is working again.
Thanks for the help. and I'll close cases.

**Comment by Bigjohn4** [comment]
thanks for all the help
