### ISSUE TITLE
DVD won't mount, ripping aborted

### ISSUE THREAD

**Issue by mg-man** [automatic-ripping-machine/automatic-ripping-machine#235]
### Description
First, I have to say ARM is *awesome*!!  But... I do have a small number of DVDs [less than a dozen out of >300!] that refuse to mount / rip.  When trying to rip them, I get a popup with information similar to the below:

Error mounting /dev/sr1 at /media/mlc/THE_RIGHT_STUFF_SIDEB_16X9EPAL1: Command-line `mount -t "udf" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8" "/dev/sr1" "/media/mlc/THE_RIGHT_STUFF_SIDEB_16X9EPAL1"' exited with non-zero exit status 32: mount: /dev/sr1 is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/sr1,
       missing codepage or helper program, or other error

### Environment
Ubuntu 16.04 LTS
ARM version = * master

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
sorry, not exactly sure how to do this

**Comment by muckngrind4** [comment]
@mg-man Glad you are enjoying ARM. 

I wonder if your DVDs are iso9660. Can you try mounting them manually using the command in the log above but replacing "udf" with "iso9660" and seeing if it is successful?

**Comment by mg-man** [comment]
Thanks for the quick response... yes, it looks I can mount this one with iso9660... and when I do, I can see the video_ts directory.  Is there something I can do to temporarily (or permanently?) cater for these sort of DVDs?

**Comment by muckngrind4** [comment]
Ahh...  Yes, case matters.  This is fixed in v2, but you should be able to fix it in v1 by changing a line in indentify.sh.  Change this line (line 79):
`		if [[ -d /mnt/${DEVNAME}/VIDEO_TS || -d /mnt/${DEVNAME}/BDMV || -d /mnt/${DEVNAME}/HVDVD_TS || $(ls -laR /mnt/${DEVNAME}/ 2>/dev/null |grep -P "HVDVD_TS" |wc -l) == 1 ]]; then
`
to
`		if [[ -d /mnt/${DEVNAME}/VIDEO_TS || -d /mnt/${DEVNAME}/video_ts || -d /mnt/${DEVNAME}/BDMV || -d /mnt/${DEVNAME}/HVDVD_TS || $(ls -laR /mnt/${DEVNAME}/ 2>/dev/null |grep -P "HVDVD_TS" |wc -l) == 1 ]]; then`

Let me know if it works...

**Comment by mg-man** [comment]
Thanks!  I'm away for the next week, but will try it out and report back soon as I'm back.

**Comment by muckngrind4** [comment]
Closing.  Feel free to reopen if this doesn't fix your issue.

**Comment by mg-man** [comment]
Hi... just tried the mod you suggested and I still get an error : 

Error mounting /dev/sr0 at /media/mlc/THE_RIGHT_STUFF_SIDEA_16X9EPAL1: Command-line `mount -t "udf" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8" "/dev/sr0" "/media/mlc/THE_RIGHT_STUFF_SIDEA_16X9EPAL1"' exited with non-zero exit status 32: mount: /dev/sr0 is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/sr0,
       missing codepage or helper program, or other error

From the message, it looks like it's still trying to mount the DVD as "udf"...  

Is there something else I need to change to have it try "iso9660" as well?

**Comment by mg-man** [comment]
OK... so... since I'm in the UK and thus you're not up yet... ;-)  I've set ARM_CHECK_UDF=false.

Now, I get an error pop-up... *but* ripping (video, not data) *does* start... strange.

I didn't capture the popup error this time, since I'd assumed another abort - but then ripping started.  I'll capture the popup when this rip is done and report back.

**Comment by mg-man** [comment]
OK... so... grabbed the error this time... 

Error mounting /dev/sr0 at /media/mlc/THE_RIGHT_STUFF_SIDEA_16X9EPAL1: Command-line `mount -t "udf" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8" "/dev/sr0" "/media/mlc/THE_RIGHT_STUFF_SIDEA_16X9EPAL1"' exited with non-zero exit status 32: mount: /dev/sr0 is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/sr0,
       missing codepage or helper program, or other error

Looks to be the same as before.  So it must be something in the 'ARM_CHECK_UDF' process that's causing the abort?

**Comment by muckngrind4** [comment]
Can you post the line from your fstab file that reference this drive?  Or post your whole fstab?

**Comment by mg-man** [comment]
Sure... I was wondering if that could be the issue... (I can hack my way 'round Linux, but am no expert)

Here's what I have (which curiously, is missing both my drives!)...

# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system>                           <mount point>   <type>       <options>                 <dump>  <pass>
# / was on /dev/sda5 during installation
UUID=eb31741e-a785-4c23-869e-95d368159fc4 /               ext4         errors=remount-ro         0       1
# swap was on /dev/sda6 during installation
UUID=eceb3a3f-0df3-4482-a62f-77971ce402e6 none            swap         sw                        0       0
# ARM media on /dev/sdb1
/dev/sdb1                                 /mnt/media/ARM  ext4         rw                        2       2

I presume my drives are /dev/sr0  [DVDRW, with DVDRAM support] and /dev/sr1  [Blu-Ray RW]

Just to confirm above, I *have* managed to rip the DVDs that were previously aborting by changing ARM_CHECK_UDF=false.  I still got the pop-up, but the process did proceed to rip the DVD - before it would just eject.  I did notice, however, that the 'rips' all went into .../Unidentified/... and had *no* movie detail information (even though as you can see above, they were recognised).

Hope all this helps.  Thanks again for an awesome 'machine'!!

**Comment by muckngrind4** [comment]
Yes, you'll need to have entries in your fstab for each drive.  Take a look at the section of the [readme](https://github.com/automatic-ripping-machine/automatic-ripping-machine) under "set up drives".  Make sure you create the mount points for each drive and add then entries to your fstab file.  Here are what the entries in my fstab looks like (I have two drives also):
`/dev/sr0  /mnt/dev/sr0  udf,iso9660  user,noauto,exec,utf8  0  0`
`/dev/sr1  /mnt/dev/sr1  udf,iso9660  user,noauto,exec,utf8  0  0`

You have two issues and this should fix both.  First, it looks like you have a few dvds that are iso9660 (The Right Stuff log above is one of them). This will allow them to be mounted correctly.  Second, ARM can't identify the type of dvd it is (movie, etc) or the title and apply any subsequent intelligence unless it can mount the dvd and inspect the file system.  This should fix that also.

**Comment by mg-man** [comment]
Thanks... and my apols for not RTFM'ing...  :-(

However... when I add the drives to fstab... I now don't get the popup... yea!  *but*... the DVD is also spat out almost immediately... boo!  Here are the last 3 lines of the log...

`identified udf`
`found THE_RIGHT_STUFF_SIDEA_16X9EPAL1 on /dev/sr0`
`identified udf as data`

As I mentioned previously, if I set ARM_CHECK_UDF=false, the DVD rips... but I don't get any 'pretty' names, etc...  

Let me know what else I can try.  Thanks!

**Comment by muckngrind4** [comment]
Set ARM_CHECK_UDF to true.  When it's false, ARM doesn't try to mount the drives.  If that doesn't work post the full log (drag & drop on comment) and I'll check it out.

**Comment by mg-man** [comment]
I do have ARM_CHECK_UDF set to true, and the DVD is spat out almost immediately.  Adding the drives to fstab seems to cure the pop-up error only.  I'll attach the log... 

[THE_RIGHT_STUFF_SIDEA_16X9EPAL1.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2325570/THE_RIGHT_STUFF_SIDEA_16X9EPAL1.log)
