### ISSUE TITLE
Clicking "Change Settings" Button in Web Portal Generates an AttributeError

### ISSUE THREAD

**Issue by bwbloom** [automatic-ripping-machine/automatic-ripping-machine#406]
### Description
When I click the "Change Settings" button in the web portal I get the following error on the webpage:
AttributeError: 'Config' object has no attribute 'pretty_table'

### Environment
Ubuntu 18.04.5 LTS running on bare metal
ARM version 2.2.0-dev

### Log file
Here is what is output on the webpage:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/arm/arm/ui/routes.py", line 103, in changeparams
    app.logger.debug(config.pretty_table())
AttributeError: 'Config' object has no attribute 'pretty_table'
```

**Comment by 1337-server** [comment]
You're not using version 2.2.0 or your files have been mixed up as 
```  
File "/opt/arm/arm/ui/routes.py", line 103, in changeparams
    app.logger.debug(config.pretty_table() 
``` 
line doesn't exist in version 2.2.0.

This problem is most likely caused by the ARM ui being a higher version than the rest of your ARM filesystem. 

You will either need to update the rest of the files (The main one being /opt/arm/arm/models/models.py) 
Or 
Fully downgrade to v2.2.0 from this repo.

**Comment by 1337-server** [comment]
I apologise. I was mistaken, this is a bug in the coding.

I have made a mistake with the last commited pull request. That line is in the current repo, but it shouldn't be as the models.py doesn't have the new code to handle it.

 You can edit the routes.py and remove line 103 this should fix the error.

**Comment by bwbloom** [comment]
No worries. The downside is I think I may have kind of botched a couple of things trying to troubleshoot.

I commented line 103 out and all of a sudden the web portal will no longer work. I uncommented the line and still no dice. I can't get there either via the ip address or the local hostname.

I rebooted the system and still can't get there.

**Comment by 1337-server** [comment]
Did you setup the webui to log to file ? 

It should be trying to output a log file to let you know if there is a problem with the webui.

Did you setup ARMui as a service ?

**Comment by bwbloom** [comment]
Not sure I saw anything in the Readme file about that. Do you have a reference on how to do that?

**Comment by 1337-server** [comment]
The readme doesn't have this info - i have made a wiki here with a lot more detailed instructions for ARM
https://github.com/1337-server/automatic-ripping-machine/wiki/Setting-up-ARM-manually-(Ubuntu)#installing-the-armui-service

**Comment by bwbloom** [comment]
Sorry, but this is a touch beyond my level.

I am barely understanding what is going on at this point...

I tried to create that service but am unclear which lines am I supposed to uncomment, and should I adjust the file paths, or are those variables that are pulling from my arm.yaml log location?

Either way, when I try to start armui I get the following error:
```
Failed to start armui.service: Unit armui.service is not loaded properly: Exec format error.
See system logs and 'systemctl status armui.service' for details.
```

I am not sure I understand where to check the 'systemctl status armui.service', but this is what I can find in `/var/log/syslog`:
```
Mar 10 14:47:00 arm systemd[1]: /etc/systemd/system/armui.service:14: Executable path is not absolute: python3 /opt/arm/arm/runui.py
Mar 10 14:47:57 arm systemd[1]: slim.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 14:47:57 arm systemd[1]: slim.service: Failed with result 'exit-code'.
Mar 10 14:47:58 arm systemd[1]: slim.service: Service hold-off time over, scheduling restart.
Mar 10 14:47:58 arm systemd[1]: slim.service: Scheduled restart job, restart counter is at 20.
```

**Comment by 1337-server** [comment]
You may need to change 
`ExecStart=python3 /opt/arm/arm/runui.py`
inside the service file to
`ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py`

You will also need to uncomment these lines and put in the path you would like the log file for the armui to be
```
#StandardOutput=append:/PATH-TO-MY-LOGFILES/WebUI.log
#StandardError=append:/PATH-TO-MY-LOGFILES/WebUI.log
```

If that doesn't work i'm not sure how to help beside deleting the /opt/arm folder and starting again.
The only time i have seen that error is when I've pulled containers for x64 on my Raspberry pi, but that doesn't apply as you're running ubuntu.

**Comment by bwbloom** [comment]
Well, restarting the service got the website up and running and the commenting out of line 103 fixed the Change Settings on the website so that's working.

Problem is I do not seem to be getting any of the `WebUI.log` outputs. I am outputting to the same log directory as the arm logs, but no `WebUI.log`  file is showing up.

Is this expected since I am no longer having errors?

**Comment by 1337-server** [comment]
Even if there are no errors it should still output to the log.

Did you remove the # from the about lines ?

**Comment by bwbloom** [comment]
Correct.
Here is what I have in the armui.service:
```
[Unit]
Description=Arm service
## Added to force armui to wait for network
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
## Add your path to your logfiles if you want to enable logging
## Remember to remove the # at the start of the line
StandardOutput=append:/home/arm/logs/WebUI.log
StandardError=append:/home/arm/logs/WebUI.log
Restart=always
RestartSec=3
ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py
[Install]
WantedBy=multi-user.target
```

**Comment by 1337-server** [comment]
can you try to run

```
sudo systemctl daemon-reload
sudo systemctl enable armui.service
sudo systemctl restart armui.service 
```

**Comment by bwbloom** [comment]
No luck. Here is everything I can see in the output directory:
```
bwbloom@arm:/home/arm/logs$ ls
 28_WEEKS_LATER.log                     'PAW_PATROL_NA.log '     WILD_WEST_S1_D6.log          WWW_S1_D2.log                WWW_S1_D7.log
'28_WEEKS_LATER.log '                   'System_Reserved.log '  'WILD_WEST_S1_D6.log '       'WWW_S1_D2.log '             'WWW_S1_D7.log '
 28_WEEKS_LATER.log.bak                  WILD_WEST_S1_D4.log     WWW_S1_D1_161536367528.log   WWW_S1_D3_161536368082.log
 empty.log                              'WILD_WEST_S1_D4.log '   WWW_S1_D1_161540250324.log   WWW_S1_D3_161540250703.log
'Operating_System.log '                  WILD_WEST_S1_D5.log     WWW_S1_D1.log                WWW_S1_D3.log
'PAW_PATROL_GREAT_PIRATE_RESCUE_.log '  'WILD_WEST_S1_D5.log '  'WWW_S1_D1.log '             'WWW_S1_D3.log '
```

**Comment by 1337-server** [comment]
can you try 
`sudo systemctl status armui.service`

just incase the arm ui is still running from the arm_wrapper.sh

**Comment by bwbloom** [comment]
Here's what I get:
```
● armui.service - Arm service
   Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: en
   Active: active (running) since Wed 2021-03-10 16:57:34 PST; 36min ago
 Main PID: 4626 (python3)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/armui.service
           ├─4626 /usr/bin/python3 /opt/arm/arm/runui.py
           └─4653 /usr/bin/python3 /opt/arm/arm/runui.py

Mar 10 16:57:35 arm python3[4626]:    Use a production WSGI server instead.
Mar 10 16:57:35 arm python3[4626]:  * Debug mode: on
Mar 10 16:57:35 arm python3[4626]:  * Running on http://192.168.86.36:8080/ (Pre
Mar 10 16:57:35 arm python3[4626]:  * Restarting with stat
Mar 10 16:57:35 arm python3[4626]:  * Debugger is active!
Mar 10 16:57:35 arm python3[4626]:  * Debugger PIN: 163-232-579
Mar 10 16:57:38 arm python3[4626]: 192.168.86.164 - - [10/Mar/2021 16:57:38] "GE
Mar 10 16:57:38 arm python3[4626]: 192.168.86.164 - - [10/Mar/2021 16:57:38] "GE
Mar 10 17:00:30 arm python3[4626]: 192.168.86.164 - - [10/Mar/2021 17:00:30] "GE
Mar 10 17:00:30 arm python3[4626]: 192.168.86.164 - - [10/Mar/2021 17:00:30] "GE
```

**Comment by 1337-server** [comment]
Not sure why this isn't logging

Maybe its the append in the service file ? But cant think of anything that would stop it logging
```
StandardOutput=file:/home/arm/logs/WebUI.log
StandardError=file:/home/arm/logs/WebUI.log
```

**Comment by bwbloom** [comment]
Weird. Total head scratcher. 
I manually created a WebUI.log file and it doesn't seem to be receiving the outputs either. Would I have to do some permission monkeying to allow the service to write to it?

**Comment by 1337-server** [comment]
You need to restart the service whenever you delete or change the logfile, at least in my own experience on Debian
You might need to change the permissions to be writeable for others but that's out of my depth.

**Comment by bwbloom** [comment]
Wow. Just baffled. Restarting the service didn't work, manually creating the files with universal permissions was a no go, rebooting the machine didn't do it. These logs just won't show up.

Either way, everything seems to be working so I am going to close the issue.

Thanks
