### ISSUE TITLE
Ripping Cd's not working

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#435]
### Description

I seem to not be able to rip cd's .. i get the following in the empty.log,  could this be a permissions error somewhere?

06-06-2021 20:36:33] INFO ARM: utils.get_cdrom_status Failed to open device /dev/loop5 to check status.
[06-06-2021 21:01:52] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
[06-06

### Environment
ubuntu 20.04
latest 

### Log file
06-06-2021 20:36:33] INFO ARM: utils.get_cdrom_status Failed to open device /dev/loop5 to check status.
[06-06-2021 21:01:52] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
[06-06

**Comment by 1337-server** [comment]
Can you try triggering ARM manually to see if it outputs any more details ?

**Comment by coacharnold1** [comment]
So this is still not working.   I cannot find the manual trigger instructions,  if you can repost them.   ... But if I just inserted a CD and got these 4 lines. (in the empty log file) 

[14-06-2021 21:27:22] INFO ARM: utils.get_cdrom_status Failed to open device /dev/loop9 to check status.
[14-06-2021 21:27:32] INFO ARM: utils.get_cdrom_status Failed to open device /dev/loop10 to check status.
[14-06-2021 21:27:36] INFO ARM: utils.get_cdrom_status Failed to open device /dev/loop5 to check status.
[14-06-2021 21:27:37] INFO ARM: utils.get_cdrom_status Failed to open device /dev/loop10 to check status.

DVD rips fine,   but is very slow (24hrs) ....  I know this has been addressed with another recent user as being a hardware issues, however this same hardware, the older version of ARM ripped the same DVD's in 4 to 6 hours.  Is there possibly a cofig issue?

**Comment by coacharnold1** [comment]
Found it ... sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0

when I run that command , I  get nothing

**Comment by 1337-server** [comment]
Can you check that the music output folder exists and is writeable ?

You will need to check the .abcde.conf for the output path.

**Comment by coacharnold1** [comment]
well .... here's the path - OUTPUTDIR="/home/arm/Music
THere wasn't a Folder.   I thought it was supposed to be made by the script if it wasn't there?   I made one and gave it 777 permissions ...  still no output.  DO I need to configure the .abcde.conf file out of the box?  I assumed it was ready to go on install.  

I also feel like a raw file isn't getting made from the DVD to transcode .... that this is the issue with speed.  I just looked at the tail section of the last video I ripped .... which was actually my wedding video ... (titled sonia and time.mkv for some reason as opposed to sonia and tim .. anyway ... )   here's the end of that log ...  

10-06-2021 00:17:01] DEBUG ARM: models.eject we unmounted disc/dev/sr0
[10-06-2021 00:17:06] DEBUG ARM: models.eject failed to eject/dev/sr0
[10-06-2021 00:17:06] DEBUG ARM: main.main New Title is sonia_and_time
[10-06-2021 00:17:06] INFO ARM: main.main Type is 'unknown' or we dont have a nice title - Moving title_01.mkv to /home/arm/media/completed/unidentified/sonia_and_time
[10-06-2021 00:17:06] DEBUG ARM: utils.move_files Arguments: /home/arm/media/transcode/unidentified/sonia_and_time : title_01.mkv : False : sonia_and_time : True
[10-06-2021 00:17:06] DEBUG ARM: utils.make_dir Creating directory: /home/arm/media/completed/unidentified/sonia_and_time
[10-06-2021 00:17:06] INFO ARM: utils.move_files Track is the Main Title.  Moving 'title_01.mkv' to /home/arm/media/completed/unidentified/sonia_and_time
[10-06-2021 00:17:06] INFO ARM: utils.scan_emby EMBY_REFRESH config parameter is false.  Skipping emby scan.
[10-06-2021 00:17:06] INFO ARM: main.main Removing raw path - None
[10-06-2021 00:17:06] DEBUG ARM: main.main No raw files found to delete in None - lstat: path should be string, bytes or os.PathLike, not NoneType
[10-06-2021 00:17:06] INFO ARM: main.main Removing raw path - /home/arm/media/transcode/unidentified/sonia_and_time
[10-06-2021 00:17:06] INFO ARM: main.main Removing raw path - /dev/sr0
[10-06-2021 00:17:08] DEBUG ARM: main.main No raw files found to delete in /dev/sr0 - [Errno 123] No medium found: '/dev/sr0'
[10-06-2021 00:17:08] INFO ARM: main.main ARM processing complete

**Comment by 1337-server** [comment]
.abcde.conf should work right out of the box for most cases. But its very configurable.

The music directory is the only directory ARM doesn't make as the directory is set in .abcde.conf and this could cause issues if the users changes the directory in the .abcde.conf 

Have you check for any messages or installed postfix  ? I've added instructions here https://github.com/1337-server/automatic-ripping-machine/wiki/General-Troubleshooting#email-notifications

**Comment by coacharnold1** [comment]
woops didn't realize i could attach a file here,
[sonia_and_time.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6659047/sonia_and_time.log)

just installed postfix .... i'm new to this part , so i'm not sure what supposed to happen,  also I started a DVD in the process of all this to see how that was working ....

**Comment by 1337-server** [comment]
You have a large number of disk read errors, could you try re-running the rip with MakeMKV you would need to change `RIPMETHOD: "backup"` to `RIPMETHOD: "mkv"` in your arm.yaml.  This will first rip the disc to your hard drive using MakeMKV instead of HandBrake and may speed up transcode times as it doest need to worry about disc read errors.

But I'm not sure if this is causing the longer transcode times. As your CPU is a low power model. The difference in transcoding time could be due to the changes HandBrake has gone through. I couldn't be 100% on this, and you would need to modify/tweek the handbrake profile to try to reach a similar transcode speed. After testing using MakeMKV to remove the disc read errors issue.

As for postfix you should be able to type `mail` in a terminal/ssh as the arm user to see any errors that would kill ARM before logging starts (db errors, permission errors, python coding errors, etc)

You can also tail the syslog when you insert a disc to see if its throwing out any useful information. `tail -f /var/log/syslog`

**Comment by coacharnold1** [comment]
ok ... so you answered a questio I didn't ask ...LOL .... the ripmethod ....    I will change that and see what happens ... I was thinking that .

HMMMM  OMDB ...  here's what I have in my arm.raml file 

OMDB_API_KEY: "365a2891"

Here's the email from OMdB
________________________
Here is your key: 365a2891

Please append it to all of your API requests,
_______________________________

What did I miss?

Here's what I get from the mail 

mount: /mnt/dev/sr0: WARNING: device write-protected, mounted read-only.
umount: /dev/sr0: not mounted.

**Comment by 1337-server** [comment]
You should remove your key.

That looks correct, not sure why its saying your key isn't valid.

The output from mail looks normal. Ill spin up a VM to see if i can reproduce this issue.

**Comment by coacharnold1** [comment]
just toook the ombd key out ... cancelled the rip that was going and rebooted/restarted everything .... of course the new rip didn't get anything from omdb either (no key) .. should take a few hours I assume ... everything is going through makeMKV ....  honestly this new version of ARM is amazing.  and I realize I just need to get it tweaked the right way .  Thanks for your help.. I'll keep plugging away tommorw.    I'm really hoping to figure out why the CD ripper isn't going?

**Comment by coacharnold1** [comment]
as I was typing the above .... the rip ended and it spit the DVD out ... on to transcoding ... it says ETS 1.5 hrs ....  looks like that speeds things up A LOT!!

**Comment by 1337-server** [comment]
Glad that helped speed things up

I have confirmed that CD's are bugged. Its not just you, ill try narrowing down the issue.

**Comment by coacharnold1** [comment]
woooooo - hoooo !!!!!   Glad it wasn't just me.   anything I can do to help test out the bug ... please let me know.  Thanks for letting me know .

**Comment by 1337-server** [comment]
https://github.com/1337-server/automatic-ripping-machine/commit/3f7ec945032c2c7c7d5313fe219bbb774203738f

This should fix the cd issues.

**Comment by coacharnold1** [comment]
Sorry to do this ... what is the procedure for updating from git without effecting my arm.yaml file?

**Comment by 1337-server** [comment]
cd /opt/arm
    git pull

Should be all that you need.

**Comment by coacharnold1** [comment]
OK .....  Seems all is almost  well in camp ....  
CD's are now being ripped.  They do not eject, which I realize has got to be something simple,  I just cant seem to find it.

I tried re inputting my omdb key into  arm.yaml and am still getting a key error.  

utils.call_omdb_api omdb call failed with error - HTTP Error 401: Unauthorized

any thoughts?   SHould I close this and open a new topic?

T

**Comment by 1337-server** [comment]
For CD's the eject is controlled by the .abcde.conf (it should be `/home/arm/.abcde.conf` but it will be hidden)

You would need to modify the .abcde.conf to find `#EJECTCD=y` and change it to `EJECTCD=y`

Its probably best to open a new issue for omdb.

**Comment by coacharnold1** [comment]
Thanks!!!!!!
